name: Build and tests

on: [push]

jobs:
    build_container:
        if: github.repository == 'rawsample/avatar2'
        runs-on: ubuntu-20.04
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Generate Dockerfile
              run: python3 ${{ github.workspace }}/generate_dockerfile.py --endpoint_list avatar-qemu panda --qemu_targets arm-softmmu mips-softmmu
            - name: Build docker container

