name: Build and tests
on: [push]
jobs:
    build_container:
        if: github.repository == 'rawsample/avatar2'
        runs-on: ubuntu-20.04
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Generate Dockerfile
              run: python3 ${{ github.workspace }}/generate_dockerfile.py --endpoint_list avatar-qemu panda --qemu_targets arm-softmmu mips-softmmu

            - name: Build docker container
              run: docker build --tag avatar2 .

            - name: hello_world
              run: docker exec avatar2 bash -c 'cd avatar2/ && python3 ./tests/hello_world.py'

            - name: Save and compress docker image
              run: |
                  docker save avatar2 -o avatar2-image.tar
                  tar zcvf avatar2-image.tar.gz avatar2-image.tar
            - name: Upload docker image
              uses: actions/upload-artifact@v2
              with:
                  name: docker-artifact
                  path: ${{ github.workspace }}/avatar2-docker-image.tar
                  retention-days: 1

    tests:
        if: github.repository == 'rawsample/avatar2'
        runs-on: ubuntu-20.04
        needs: [build_container]
        steps:
            - name: Download docker image
              uses: actions/download-artifact@v2
              with:
                  name: docker-artifact
                  path: ${{ github.workspace }}/avatar2-docker-image.tar
            - name: Load docker image
              run: |
                  tar xvf avatar2-image.tar.gz avatar2-image.tar
                  docker load --input ${{ github.workspace }}/avatar2-docker-image.tar
                  docker image ls

            - name: Run avatar2 container
              run: |
                  docker run -v /home/travis/build/$TRAVIS_REPO_SLUG:/avatar2 --name avatar2 --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -dit avatar2
                  docker exec avatar2 pip3 install nose

            - name: hello_world
              run: docker exec avatar2 bash -c 'cd avatar2/ && python3 ./tests/hello_world.py'
            - name: test_remote_memoryprotocol
              run: docker exec avatar2 bash -c 'cd avatar2/ && nosetests ./tests/test_remote_memoryprotocol.py'
            - name: test_gdbprotocol
              run: docker exec avatar2 bash -c 'cd avatar2/ && nosetests ./tests/test_gdbprotocol.py'
            - name: test_gdbplugin
              run: docker exec avatar2 bash -c 'cd avatar2/ && nosetests ./tests/test_gdbplugin.py'
            - name: test_inceptionprotocol
              run: docker exec avatar2 bash -c 'cd avatar2/ && nosetests ./tests/test_inceptionprotocol.py'
            - name: gdb_memory_map_loader
              run: docker exec avatar2 bash -c 'cd avatar2/ && python3 ./tests/gdb_memory_map_loader.py'

            - name: test_qemutarget ARM
              run: docker exec avatar2 bash -c 'cd avatar2/ && AVATAR2_GDB_EXECUTABLE=gdb-multiarch AVATAR2_ARCH=ARM AVATAR2_QEMU_EXECUTABLE=qemu-system-arm nosetests ./tests/test_qemutarget.py'
            - name: test_qemutarget MIPS
              run: docker exec avatar2 bash -c 'cd avatar2/ && AVATAR2_GDB_EXECUTABLE=gdb-multiarch AVATAR2_ARCH=MIPS AVATAR2_QEMU_EXECUTABLE=qemu-system-mips nosetests ./tests/test_qemutarget.py'
            - name: test_pyperipheral
              run: docker exec avatar2 bash -c 'cd avatar2/ && AVATAR2_GDB_EXECUTABLE=gdb-multiarch AVATAR2_QEMU_EXECUTABLE=qemu-system-arm nosetests ./tests/pyperipheral/test_pyperipheral.py'

            - name: test_qemutarget ARM PANDA
              run: docker exec avatar2 bash -c 'cd avatar2/ && AVATAR2_GDB_EXECUTABLE=gdb-multiarch AVATAR2_ARCH=ARM AVATAR2_QEMU_EXECUTABLE=panda-system-arm nosetests ./tests/test_qemutarget.py'
            - name: test_qemutarget MIPS PANDA
              run: docker exec avatar2 bash -c 'cd avatar2/ && AVATAR2_GDB_EXECUTABLE=gdb-multiarch AVATAR2_ARCH=MIPS AVATAR2_QEMU_EXECUTABLE=panda-system-mips nosetests ./tests/test_qemutarget.py'
            - name: test_pyperipheral
              run: docker exec avatar2 bash -c 'cd avatar2/ && AVATAR2_GDB_EXECUTABLE=gdb-multiarch AVATAR2_QEMU_EXECUTABLE=panda-system-arm nosetests ./tests/pyperipheral/test_pyperipheral.py'
            - name: smoke: panda_thumb
              run: docker exec avatar2 bash -c 'cd avatar2/ && AVATAR2_GDB_EXECUTABLE=gdb-multiarch AVATAR2_QEMU_EXECUTABLE=panda-system-arm AVATAR2_PANDA_EXECUTABLE=panda-system-arm nosetests ./tests/smoke/panda_thumb.py'
            - name: test_pypandatarget
              run: docker exec avatar2 bash -c 'cd avatar2/ && AVATAR2_GDB_EXECUTABLE=gdb-multiarch AVATAR2_QEMU_EXECUTABLE=panda-system-arm AVATAR2_PANDA_EXECUTABLE=panda-system-arm nosetests ./tests/test_pypandatarget.py'

            - name: smoke: target_wait
              run: docker exec avatar2 bash -c 'cd avatar2/ && nosetests --processes=-1 --process-timeout=20 ./tests/smoke/target_wait.py'
            - name: smoke: 54_sync_hooks
              run: docker exec avatar2 bash -c 'cd avatar2/ && AVATAR2_GDB_EXECUTABLE=gdb-multiarch AVATAR2_QEMU_EXECUTABLE=panda-system-arm nosetests --processes=-1 --process-timeout=20 ./tests/smoke/54_sync_hooks.py'
