name: Publish to PyPI

on:
    push:
        tags:
            - 'v*' 

jobs:
    build-n-publish:
        if: |
            github.repository == 'rawsample/avatar2' && startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-20.04
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Build a binary wheel and a source tarball
              run: python3 setup.py sdist bdist_wheel

            - name: Check package
              run: |
                  pip3 install twine
                  python3 -m twine check dist/*

            - name: Publish to Test PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  user: __token__
                  password: ${{ secrets.TEST_PYPI_API_TOKEN }}
                  repository_url: https://test.pypi.org/legacy/


