name: Publish to PyPI

on:
    push:
        tags:
            - 'v*' 

jobs:
    build-n-publish:
        if: |
            github.repository == 'rawsample/avatar2' && startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-20.04
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Build a binary wheel and a source tarball
              run: python3 setup.py sdist bdist_wheel

            - name: Check package
              run: |
                  pip3 install twine
                  python3 -m twine check dist/*

                  #- name: Publish to Test PyPI
                  #  uses: pypa/gh-action-pypi-publish@release/v1
                  #  with:
                  #      user: __token__
                  #      password: ${{ secrets.TEST_PYPI_API_TOKEN }}
                  #      repository_url: https://test.pypi.org/legacy/


    docs:
        if: |
            github.repository == 'rawsample/avatar2' && startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-20.04
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
              with:
                  paths: avatar2

            - name: Check out documentation repository
              uses: actions/checkout@v2
              with:
                  repository: rawsample/avatar2-docs
                  path: avatar2-docs
                  token: ${{ secrets.PUSH_DOCS_TOKEN }}

            - name: Install Sphinx
              run: pip3 install Sphinx sphinx_rtd_theme

            - name: Build avatar2
              run: |
                  cd avatar2
                  python3 setup.py install

            - name: Build documentation
              # Generated files are located at avatar2-docs
              run: |
                  ls
                  cd avatar2/docs
                  make html

            - name: Publish documentation
              run: |
                  ls
                  cd avatar2-docs
                  git config --local user.name "github-actions[bot]"
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git commit --all -m "Update documentation"
                  git push https:://$USERNAME:$REPO_KEY@github.com/rawsample/avatar2-docs.git
              env:
                  USERNAME: github-actions[bot]
                  REPO_KEY: ${{ secrets.PUSH_DOCS_TOKEN }}







